version: '3.9'

services:
  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
  mysql:
    image: mysql:8.0.31
    restart: always
    environment:
      MYSQL_DATABASE: 'scheduled-notifications'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'