version: '3.9'
services:


  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
     - user-settings-network


  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
     - broker-network


  mysql:
    image: mysql:8.0.31
    restart: always
    environment:
      MYSQL_DATABASE: 'scheduled-notifications'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    networks:
     - notifications-manager-network


  user-settings-ms:
    build: user-settings-ms
    platform: linux/amd64
    environment:
      MONGODB_HOST: 'mongodb'
    ports:
      - '8080:8080'
    depends_on:
      - "mongodb"
    networks:
     - ms-network
     - user-settings-network


  notifications-manager-ms:
    build: notifications-manager-ms
    platform: linux/amd64
    ports:
      - '8081:8081'
    environment:
      MYSQL_URL: 'jdbc:mysql://mysql/notification_manager?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false'
      RABBITMQ_HOST: 'rabbitmq'
      USER_SETTINGS_URL: 'http://user-settings-ms:8080'
    depends_on:
      - "mysql"
      - "rabbitmq"
      - "user-settings-ms"
    networks:
     - notifications-manager-network
     - broker-network
     - ms-network


  notifications-sender-ms:
    build: notifications-sender-ms
    platform: linux/amd64
    ports:
      - '8082:8082'
    environment:
      RABBITMQ_HOST: 'rabbitmq'
      USER_SETTINGS_URL: 'http://user-settings-ms:8080'
    depends_on:
      - "rabbitmq"
      - "user-settings-ms"
    networks:
     - ms-network 
     - broker-network


networks:
  user-settings-network:
  notifications-manager-network:
  broker-network:
  ms-network: