server:
  port: 8081

spring:
  rabbitmq:
    username: admin
    password: admin
    host: ${RABBITMQ_HOST:localhost}
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost/notification_manager?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false}
    username: root
    password: root
    platform: mysql
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update

app:
  notifications:
    queue: notifications-queue
    scheduler:
      cron: "*/10 * * * * *"
      max-notifications-per-iteration: 100
  user-settings:
    feign-client:
      name: user-settings-feign-client
      url: ${USER_SETTINGS_URL:http://localhost:8080}